#You must set up the same Synergy token on all your servers
synergy-plugin-messaging: {}

#Get your token in the OpenAi developer dashboard
openai:
  enabled: false
  temperature: 0.7
  response-size: 64
  token: token

#Set up Discord channels and connect them to the Minecraft chat.
#You can also make a chatbot with any personality you want
discord:
  enabled: false
  channels: {}
  bot-token: token
  gpt-bot:
    enabled: false
    personality: 'Act as a cat. Answer this question in a cat style: %MESSAGE%'
    name: Stepan
  hightlights:
    enabled: false
    channels:
    - '00000000000000000'
    reaction-emoji: ♥
  
#This feature replaces special keys in the text with translations in different languages.
#Edit the locales.yml file and swap out the text in the third-party plugins' messages files with Synergy translation keys
#ProtocolLib is required
localizations:
  enabled: true
  default-language: en
  
web-server:
  enabled: false
  port: 8192
  
#NuVotifier is required
votifier:
  enabled: false
  monitorings:
  - https://example.com/vote/example
  rewards:
  - eco give %PLAYER% 1
