name: Synergy
main: me.synergy.brains.Spigot
version: 0.0.1
api-version: 1.16
author: mrbear25
softdepend: [Authme, PlaceholderAPI, ProtocolLib, Votifier]
description: Basic tools and server messaging plugin
commands:
    synergy:
        description: Synergy
        usage: synergy-command-usage /<command>
    vote:
        description: Vote
        usage: synergy-command-usage /<command>
    chat:
        description: Chat
        usage: synergy-command-usage /<command>
    colors:
        description: Custom colors list
        usage: synergy-command-usage /<command>
    discord:
        description: Discord
        usage: synergy-command-usage /<command>
    language:
        description: Language
        usage: synergy-command-usage /<command>